region       = "us-east-1"
cluster_name = "dns-alb"
namespace    = "kube-system"
external_dns_irsa_role_name = "external-dns"
oidc_provider_url = "oidc.eks.us-east-1.amazonaws.com/id/A5AED8D6E454AB2B80DCF7074B4963BC"
